import {\n  Injectable,\n  NestInterceptor,\n  ExecutionContext,\n  CallHandler,\n  Logger\n} from '@nestjs/common';\nimport { Observable } from 'rxjs';\nimport { tap } from 'rxjs/operators';\nimport { PrismaService } from '../../prisma/prisma.service';\n
@Injectable()\nexport class AuthLoggingInterceptor implements NestInterceptor {\n  private readonly logger = new Logger(AuthLoggingInterceptor.name);\n
  constructor(private prisma: PrismaService) {}\n
  intercept(context: ExecutionContext, next: CallHandler): Observable<any> {\n    const request = context.switchToHttp().getRequest();\n    const { method, path, user, body } = request;\n
    // Log authentication attempts\n    if (path.includes('/auth/signin') || path.includes('/auth/signup')) {\n      this.logAuthAttempt(method, path, body.email, 'ATTEMPT');\n    }\n
    return next.handle().pipe(\n      tap({\n        next: (data) => {\n          // Successful authentication\n          if (path.includes('/auth/signin') || path.includes('/auth/signup')) {\n            this.logAuthAttempt(method, path, body.email, 'SUCCESS');\n          }\n
          // Password change logging\n          if (path.includes('/auth/change-password')) {\n            this.logPasswordChange(user?.id);\n          }\n
          // Token refresh logging\n          if (path.includes('/auth/refresh')) {\n            this.logTokenRefresh(user?.id);\n          }\n        },\n        error: (error) => {\n          // Failed authentication attempts\n          if (path.includes('/auth/signin') || path.includes('/auth/signup')) {\n            this.logAuthAttempt(method, path, body.email, 'FAILED', error.message);\n          }\n        }\n      })\n    );\n  }\n
  private async logAuthAttempt(\n    method: string,\n    path: string,\n    email: string,\n    status: 'ATTEMPT' | 'SUCCESS' | 'FAILED',\n    errorMessage?: string\n  ) {\n    try {\n      await this.prisma.authLog.create({\n        data: {\n          method,\n          path,\n          email,\n          status,\n          errorMessage,\n          timestamp: new Date()\n        }\n      });\n\n      // Log to console for immediate visibility\n      this.logger.log(`Auth ${status}: ${email} - ${path}`);\n    } catch (error) {\n      // Fallback logging if Prisma fails\n      this.logger.error(`Failed to log auth attempt: ${error.message}`);\n    }\n  }\n
  private async logPasswordChange(userId?: string) {\n    try {\n      await this.prisma.authLog.create({\n        data: {\n          method: 'PATCH',\n          path: '/auth/change-password',\n          userId,\n          status: 'PASSWORD_CHANGE',\n          timestamp: new Date()\n        }\n      });\n\n      this.logger.log(`Password changed for user: ${userId}`);\n    } catch (error) {\n      this.logger.error(`Failed to log password change: ${error.message}`);\n    }\n  }\n
  private async logTokenRefresh(userId?: string) {\n    try {\n      await this.prisma.authLog.create({\n        data: {\n          method: 'POST',\n          path: '/auth/refresh',\n          userId,\n          status: 'TOKEN_REFRESH',\n          timestamp: new Date()\n        }\n      });\n\n      this.logger.log(`Token refreshed for user: ${userId}`);\n    } catch (error) {\n      this.logger.error(`Failed to log token refresh: ${error.message}`);\n    }\n  }\n}"} 